# Hibernate and JPA Settings
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql: true
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create-drop
        ejb:
          naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        id:
          new_generator_mappings: false
        bytecode:
          use_reflection_optimizer: false
# Primary DataSource config
datasource:
  primary:
    jdbc-url: jdbc:h2:mem:datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      poolName: PrimaryDataSourceJPAHikariCP
      connection-timeout: 30000
      minimumIdle: 5
      maximum-pool-size: 5
      idleTimeout: 30000
      maxLifetime: 2000000
