# Hibernate and JPA Settings
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: false # enable with logger
        format_sql: true # 'true' for dev purpose
        hbm2ddl:
          auto: create-drop
        ejb:
          naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        temp:
          use_jdbc_metadata_defaults: false #Disabling contextual LOB creation error
        bytecode:
          use_reflection_optimizer: false
# Primary DataSource config
datasource:
  primary:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:postgresql://localhost:5432/testdb?currentSchema=testingjpa
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    destroy-method: shutdown
    connection-test-query: SELECT 1
    poolName: PrimaryDataSourceJPAHikariCP
    connection-timeout: 30000
    minimumIdle: 5
    maximum-pool-size: 10
    idleTimeout: 30000
    maxLifetime: 2000000
    useServerPrepStmts: true
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useUnicode: true
    characterEncoding: utf-8
